//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardUserMap
    {
        public int DashBoardUserMapID { get; set; }
        public int DashBoardID { get; set; }
        public string UserID { get; set; }
        public bool IsOwner { get; set; }
    }
}
