//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public int WidgetID { get; set; }
        public int WidgetTypeID { get; set; }
        public int DashboardID { get; set; }
        public int DataSourceID { get; set; }
        public string WidgetTypeInputParamValues { get; set; }
        public string DataSourceInputParamValues { get; set; }
    }
}
